/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author andre
 */
import Interfaces.IExcel;
import Modelo.dto.Categorias;
import Modelo.dto.HistoriaVenta;
import Modelo.dto.Producto;
import Modelo.dto.Proveedor;
import Modelo.dto.Usuario;
import java.util.ArrayList;
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private IExcel excel;
    private Usuario usuarioA;
    private ArrayList<Producto> listaproductos;
    private ArrayList<Usuario> listausuarios;
    private ArrayList<Categorias> listacategorias;
    private ArrayList<Proveedor> listaproveedores;
    private ArrayList<HistoriaVenta> listahistorial;
    public Principal(IExcel excel,Usuario usuarioA,ArrayList<Producto> productos,
            ArrayList<Usuario> usuarios,
            ArrayList<Categorias> categorias,
            ArrayList<Proveedor> proveedores,
            ArrayList<HistoriaVenta> historial) {
        initComponents();
        this.excel = excel;
        this.usuarioA = usuarioA;
        this.listaproductos = productos;
        this.listausuarios = usuarios;
        this.listacategorias = categorias;
        this.listaproveedores = proveedores;
        this.listahistorial = historial;
        
        lblingreso.setText("Usuario: " + usuarioA.getNombreUsuario());
        lblroll.setText("Rol: " + usuarioA.getRol());
        
        if(usuarioA.getRol().equals("Administrador")){
            btnPuntoVenta.setVisible(true);
            btnGestionP.setVisible(true);
            btnInventario.setVisible(true);
            btnReportes.setVisible(true);
            btnGestionU.setVisible(true);
            btnConfig.setVisible(true);
        }
        if(usuarioA.getRol().equals("Empleado")){
            btnPuntoVenta.setVisible(true);
            btnGestionP.setVisible(true);
            btnInventario.setVisible(false);
            btnReportes.setVisible(false);
            btnGestionU.setVisible(false);
            btnConfig.setVisible(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblroll = new javax.swing.JLabel();
        btnGestionU = new javax.swing.JButton();
        btnPuntoVenta = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnGestionP = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblingreso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblroll.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N

        btnGestionU.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnGestionU.setText("Gestionar Usuarios");
        btnGestionU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUActionPerformed(evt);
            }
        });

        btnPuntoVenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnPuntoVenta.setText("Punto de Ventas");
        btnPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoVentaActionPerformed(evt);
            }
        });

        btnInventario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnGestionP.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnGestionP.setText("Gestionar Productos");
        btnGestionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnConfig.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        btnConfig.setText("Configuración");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel1.setText("Usuario: ");

        lblingreso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel3.setText("Rol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblroll, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(409, 409, 409))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(btnPuntoVenta)
                                    .addGap(101, 101, 101)
                                    .addComponent(btnGestionP))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(btnReportes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGestionU)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnConfig, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPuntoVenta)
                        .addComponent(btnGestionP)
                        .addComponent(btnInventario))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReportes)
                        .addComponent(btnGestionU)
                        .addComponent(btnConfig))
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(lblroll, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(64, 64, 64)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUActionPerformed
        System.out.print("xd");
        GestionarUsuarios vusuarios = new GestionarUsuarios(this.listausuarios);
        vusuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionUActionPerformed

    private void btnPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoVentaActionPerformed
        PuntodeVenta venta = new PuntodeVenta();
        venta.setVisible(true);
    }//GEN-LAST:event_btnPuntoVentaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnGestionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnGestionP;
    private javax.swing.JButton btnGestionU;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPuntoVenta;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblingreso;
    private javax.swing.JLabel lblroll;
    // End of variables declaration//GEN-END:variables
}
