/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import gestor_de_reportes.GestorSistema; 
import javax.swing.JOptionPane;
import java.util.logging.Level;
/**
 *
 * @author diazq
 */
public class VentanaConfiguracion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName());

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
        // Opcional: Centrar la ventana
        this.setLocationRelativeTo(null);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearBackup = new javax.swing.JButton();
        btnRestaurarBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearBackup.setText("Crear Copia de Seguridad");
        btnCrearBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBackupActionPerformed(evt);
            }
        });

        btnRestaurarBackup.setText("Restaurar Copia de Seguridad");
        btnRestaurarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCrearBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestaurarBackup)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearBackup)
                    .addComponent(btnRestaurarBackup))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void initComponentes() {

        btnCrearBackup = new javax.swing.JButton();
        btnRestaurarBackup = new javax.swing.JButton();

        // Se usa DISPOSE_ON_CLOSE para no cerrar toda la aplicació
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setTitle("Configuración del Sistema");

        btnCrearBackup.setText("Crear Copia de Seguridad");
        btnCrearBackup.addActionListener(this::btnCrearBackupActionPerformed);

        btnRestaurarBackup.setText("Restaurar Copia de Seguridad");
        // SE CONECTA EL ACTION LISTENER
        btnRestaurarBackup.addActionListener(this::btnRestaurarBackupActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCrearBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnRestaurarBackup)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearBackup)
                    .addComponent(btnRestaurarBackup))
                .addContainerGap(145, Short.MAX_VALUE))
        );
// ... código de initComponents() ...
        pack();
    }// </editor-fold>
    private void btnCrearBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBackupActionPerformed
        // Llama al metodo GestorSistema para crear el backup[cite: 53, 54] 
        GestorSistema.crearCopiaSeguridad();
        JOptionPane.showMessageDialog(null, " Copia de Seguridad creada con éxito.");
    }//GEN-LAST:event_btnCrearBackupActionPerformed

    private void btnRestaurarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarBackupActionPerformed
        // Pide confirmación antes de sobreescribir los datos 
        int confirmacion = JOptionPane.showConfirmDialog(null, 
                " ¿Está seguro de que desea restaurar los datos? Se sobreescribirán los datos actuales.", 
                "Confirmar Restauración", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Llama al método para restaurar el backup [cite: 55]
            GestorSistema.restaurarCopiaSeguridad(); 
            JOptionPane.showMessageDialog(null, " Datos restaurados con éxito. El sistema se cerrará para cargar los cambios.");
            
            // Cierra el sistema para forzar la recarga de los datos restaurados
            System.exit(0);

    }//GEN-LAST:event_btnRestaurarBackupActionPerformed

    /**
     * @param args the command line arguments
     */

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearBackup;
    private javax.swing.JButton btnRestaurarBackup;
    // End of variables declaration//GEN-END:variables
}
