/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Modelo.dto.HistoriaVenta;
import Modelo.dto.Producto;
import gestor_de_reportes.ActualizarInventario;
import gestor_de_reportes.ActualizarTablaVentas;
import gestor_de_reportes.GestorReportes; 
import java.util.ArrayList; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author diazq
 */
public class VentanaReportes extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());
    
    // 1. Declarar variables internas (para guardar las listas recibidas)
    private ActualizarInventario gestionI;
    private ActualizarTablaVentas gestionV;
    
    private ArrayList<Producto> listaGeneralP; 
    private ArrayList<HistoriaVenta> listaGeneralV; // O listaHistorial, usa el nombre que tengas en Principal.java

    // 2. Constructor MODIFICADO
    public VentanaReportes(ArrayList<Producto> listaProductos, ArrayList<HistoriaVenta> listaVentas) {
        initComponents();
        this.listaGeneralV = listaVentas;
        setLocationRelativeTo(null);
        DefaultTableModel tabla = (DefaultTableModel) tablaU.getModel();
        this.gestionV = new ActualizarTablaVentas(this.listaGeneralV, tabla);
        gestionV.actualizarTablaVentas();
        }
    

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportarInventario = new javax.swing.JButton();
        btnExportarAgotados = new javax.swing.JButton();
        btnExportarVentas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaU = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExportarInventario.setText("Exportar Inventario");
        btnExportarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarInventarioActionPerformed(evt);
            }
        });

        btnExportarAgotados.setText("Exportar Bajo Stock");
        btnExportarAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAgotadosActionPerformed(evt);
            }
        });

        btnExportarVentas.setText("Exportar Ventas");
        btnExportarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarVentasActionPerformed(evt);
            }
        });

        tablaU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idVentas", "fecha", "idUsuario", "Producto Vendido", "Cantidad", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaU);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnExportarInventario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExportarVentas)
                            .addComponent(btnExportarAgotados))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnExportarInventario)
                .addGap(38, 38, 38)
                .addComponent(btnExportarAgotados)
                .addGap(41, 41, 41)
                .addComponent(btnExportarVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarInventarioActionPerformed
        Inventario vInventario = new Inventario(this.listaGeneralP);
        vInventario.setVisible(true);
        vInventario.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarInventarioActionPerformed

    private void btnExportarAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAgotadosActionPerformed
// Llama al método de Bajo Stock [cite: 39]
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte de Stock");
    fileChooser.setSelectedFile(new java.io.File("Reporte_bajoStock.xlsx"));

    // 2. Mostrar la ventana para guardar
    int userSelection = fileChooser.showSaveDialog(this);

    // 3. ¡VERIFICAR SI EL USUARIO ELIGIÓ ALGO!
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        
        // 4. Obtener la ruta elegida
        String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
        
        // Asegurarse de la extensión .xlsx
        if (!rutaArchivo.endsWith(".xlsx")) {
            rutaArchivo += ".xlsx";
        }

        // 5. LLAMAR AL MÉTODO SOLO SI TENEMOS LA RUTA
        // (Asegúrate de pasarle la lista correcta: this.listaProductosGeneral)
        gestor_de_reportes.GestorReportes.generarReporteAgotadosExcel(this.listaGeneralP, rutaArchivo);
        
    } else {
        // Si el usuario canceló, no hacemos nada (y evitamos el error NullPointerException)
        System.out.println("Exportación cancelada por el usuario.");
    }
        // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarAgotadosActionPerformed

    private void btnExportarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarVentasActionPerformed
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte de Ventas");
    fileChooser.setSelectedFile(new java.io.File("Reporte_Ventas.xlsx"));

    // 2. Mostrar ventana de guardar
    int userSelection = fileChooser.showSaveDialog(this);

    // 3. Verificar si el usuario dio "Guardar"
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        
        // 4. ¡AQUÍ OBTENEMOS LA RUTA! (Esto es lo que te faltaba o estaba mal)
        java.io.File archivoElegido = fileChooser.getSelectedFile();
        String rutaSeleccionada = archivoElegido.getAbsolutePath();
        
        // Asegurar extensión .xlsx
        if (!rutaSeleccionada.endsWith(".xlsx")) {
            rutaSeleccionada += ".xlsx";
        }

        // 5. Llamar al gestor con la ruta CORRECTA
        gestor_de_reportes.GestorReportes.generarReporteVentasExcel(this.listaGeneralV, rutaSeleccionada);
        
    } else {
        System.out.println(">>> Exportación cancelada.");
    }
    }//GEN-LAST:event_btnExportarVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarAgotados;
    private javax.swing.JButton btnExportarInventario;
    private javax.swing.JButton btnExportarVentas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaU;
    // End of variables declaration//GEN-END:variables
}
