/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Modelo.dto.HistoriaVenta;
import Modelo.dto.Producto;
import gestor_de_reportes.GestorReportes; 
import java.util.ArrayList; 
import javax.swing.JOptionPane;
/**
 *
 * @author diazq
 */
public class VentanaReportes extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());
    
    // 1. Declarar variables internas (para guardar las listas recibidas)
    private ArrayList<Producto> listaProductos; 
    private ArrayList<HistoriaVenta> listaVentas; // O listaHistorial, usa el nombre que tengas en Principal.java

    // 2. Constructor MODIFICADO
    public VentanaReportes(ArrayList<Producto> listaProductos, ArrayList<HistoriaVenta> listaVentas) {
        initComponents();
        this.listaProductos = listaProductos;
        this.listaVentas = listaVentas;
        setLocationRelativeTo(null);
        
        }
    

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportarInventario = new javax.swing.JButton();
        btnExportarAgotados = new javax.swing.JButton();
        btnExportarVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExportarInventario.setText("Exportar Inventario");
        btnExportarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarInventarioActionPerformed(evt);
            }
        });

        btnExportarAgotados.setText("Exportar Bajo Stock");
        btnExportarAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAgotadosActionPerformed(evt);
            }
        });

        btnExportarVentas.setText("Exportar Ventas");
        btnExportarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnExportarInventario)
                .addGap(52, 52, 52)
                .addComponent(btnExportarAgotados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnExportarVentas)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarAgotados)
                    .addComponent(btnExportarVentas)
                    .addComponent(btnExportarInventario))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarInventarioActionPerformed
// Llama al método de Inventario [cite: 37]
    GestorReportes.generarReporteInventarioIExcel(listaProductos, "Reporte_Inventario.xlsx");        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarInventarioActionPerformed

    private void btnExportarAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAgotadosActionPerformed
// Llama al método de Bajo Stock [cite: 39]
    GestorReportes.generarReporteAgotadosIExcel(listaProductos, "Reporte_BajoStock.xlsx");        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarAgotadosActionPerformed

    private void btnExportarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarVentasActionPerformed
// Llama al método de Ventas (Tarea 3) [cite: 40]
    GestorReportes.generarReporteVentasExcel(listaVentas, "Reporte_Ventas.xlsx");        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarAgotados;
    private javax.swing.JButton btnExportarInventario;
    private javax.swing.JButton btnExportarVentas;
    // End of variables declaration//GEN-END:variables
}
